// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    is_special,
    is_deleted
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, name, is_special, is_deleted, created_at, updated_at
`

type CreateCategoryParams struct {
	Name      string      `json:"name"`
	IsSpecial pgtype.Text `json:"is_special"`
	IsDeleted pgtype.Bool `json:"is_deleted"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.IsSpecial, arg.IsDeleted)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSpecial,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories WHERE id = $1
RETURNING id, name, is_special, is_deleted, created_at, updated_at
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSpecial,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, is_special, is_deleted, created_at, updated_at FROM categories LIMIT 10
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsSpecial,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, is_special, is_deleted, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSpecial,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = CASE
    WHEN $1::boolean = TRUE THEN $2
    ELSE name
    END,
    is_special = CASE
    WHEN $3::boolean = TRUE THEN $4
    ELSE is_special
    END,
    is_deleted = CASE
    WHEN $5::boolean = TRUE THEN $6
    ELSE is_deleted
    END
WHERE id = $7
RETURNING id, name, is_special, is_deleted, created_at, updated_at
`

type UpdateCategoryParams struct {
	SetName      bool        `json:"set_name"`
	Name         string      `json:"name"`
	SetIsSpecial bool        `json:"set_is_special"`
	IsSpecial    pgtype.Text `json:"is_special"`
	SetIsDeleted bool        `json:"set_is_deleted"`
	IsDeleted    pgtype.Bool `json:"is_deleted"`
	ID           int32       `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.SetName,
		arg.Name,
		arg.SetIsSpecial,
		arg.IsSpecial,
		arg.SetIsDeleted,
		arg.IsDeleted,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSpecial,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
